In [1]:
import pandas as pd
import numpy as np

In [9]:
us_debt_by_day = pd.read_csv("DebtPenny_10_years.csv",index_col='Calendar Day Number')

In [10]:
us_debt_by_day

,Record Date,Debt Held by the Public,Intragovernmental Holdings,Total Public Debt Outstanding,Source Line Number,Fiscal Year,Fiscal Quarter Number,Calendar Year,Calendar Quarter Number,Calendar Month Number
Calendar Day Number,,,,,,,,,,
28,2021-05-28,2.202094e+13,6.178069e+12,2.819901e+13,1,2021,3,2021,2,5
27,2021-05-27,2.198369e+13,6.179954e+12,2.816364e+13,1,2021,3,2021,2,5
26,2021-05-26,2.200589e+13,6.181836e+12,2.818773e+13,1,2021,3,2021,2,5
25,2021-05-25,2.200534e+13,6.199345e+12,2.820468e+13,1,2021,3,2021,2,5
24,2021-05-24,2.202452e+13,6.189119e+12,2.821364e+13,1,2021,3,2021,2,5
...,...,...,...,...,...,...,...,...,...,...
6,2011-06-06,9.738557e+12,4.606101e+12,1.434466e+13,1,2011,3,2011,2,6
3,2011-06-03,9.741263e+12,4.603431e+12,1.434469e+13,1,2011,3,2011,2,6
2,2011-06-02,9.735617e+12,4.609090e+12,1.434471e+13,1,2011,3,2011,2,6
1,2011-06-01,9.736529e+12,4.608127e+12,1.434466e+13,1,2011,3,2011,2,6
31,2011-05-31,9.723456e+12,4.621212e+12,1.434467e+13,1,2011,3,2011,2,5

In [3]:
dfpd.read_csv("USFR_BalSheet_10_years.csv")

,Record Date,Account Description,Line Item Description,Position Amount (in Billions),Source Line Number,Fiscal Year,Fiscal Quarter Number,Calendar Year,Calendar Quarter Number,Calendar Month Number,Calendar Day Number
0,2020-09-30,Assets,Cash and other monetary assets,1926.9,1,2020,4,2020,3,9,30
1,2020-09-30,Assets,"Accounts receivable, net",321.2,2,2020,4,2020,3,9,30
2,2020-09-30,Assets,"Direct loans and loan guarantees receivable, net",1577.4,3,2020,4,2020,3,9,30
3,2020-09-30,Assets,"Inventories and related property, net",379.7,4,2020,4,2020,3,9,30
4,2020-09-30,Assets,"General property, plant and equipment, net",1145.0,5,2020,4,2020,3,9,30
...,...,...,...,...,...,...,...,...,...,...,...
250,2010-09-30,Liabilities,Total liabilities,16356.6,21,2010,4,2010,3,9,30
251,2010-09-30,Net position,Earmarked funds,646.9,22,2010,4,2010,3,9,30
252,2010-09-30,Net position,Non-earmarked funds,-14119.7,23,2010,4,2010,3,9,30
253,2010-09-30,Net position,Total net position,-13472.8,24,2010,4,2010,3,9,30
254,2010-09-30,Net position,Total liabilities and net position,2883.8,25,2010,4,2010,3,9,30

In [4]:
df.info()

NameError: name 'df' is not defined